apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui-deployment
spec:
  selector:
    matchLabels:
      app: todo-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: venkyramachandran82/todo-ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-ui
  labels:
    app: todo-ui
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: todo-ui